### ISSUE TITLE
Crash in collect_types prep_args

### ISSUE THREAD

**Issue by jabdoa2** [dropbox/pyannotate#13] opened 2017-11-17 13:22 UTC
When collecting types on Ubuntu 16.04 with Python 3.5 on the partially annotated Mission Pinball Framework codebase (https://github.com/missionpinball/mpf/), I get this error: 
```
  File "/usr/local/lib/python3.5/dist-packages/pyannotate_runtime/collect_types.py", line 719, in _trace_dispatch
    resolved_types = prep_args(arg_info)
  File "/usr/local/lib/python3.5/dist-packages/pyannotate_runtime/collect_types.py", line 474, in prep_args
    resolved_type = resolve_type(arg_info.locals[arg])
KeyError: 'source'
```

Changing `if not isinstance(arg, (list, dict)):` to `if not isinstance(arg, (list, dict)) and arg in arg_info.locals:` fixes this for me. Don't know it that is a proper solution.

**Comment by gvanrossum** [comment] 2017-11-17 16:56
Can you please submit a PR with the fix so I can review and test it?

**Comment by gvanrossum** [comment] 2017-11-20 15:52
Closing as duplicate of #21 (because the latter shows a small example).

**Closed by gvanrossum** 2017-11-20 15:52 UTC
